
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments



# Setup
#timezone:            your timezone # eg. Asia/Kathmandu
locale:              your locale language # eg. en_us
name:				         Shanghai Dev Life
title:               site title
tagline:             'tagline'
description:         'description'
url:                 site url
rss:                 rss feed url
baseurl:             '/shanghaidevlife/'
baseurl_posts_img:   '/shanghaidevlife/assets/images/posts/'
baseurl_featured_img: '/shanghaidevlife/assets/images/hero/'
baseurl_featured_thumbnail: '/shanghaidevlife/assets/images/thumbnail/'
baseurl_javascripts: '/shanghaidevlife/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Cesar
  url:            	 your site url
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -

    values:
      layout: "default"
